- platform: template
  sensors:
    upstairs_smoke_detected:
      friendly_name: Upstairs Smoke Detected
      device_class: smoke
      value_template: >-
        {{ is_state('sensor.upstairs_smoke_alarm_alarm_level', '255') and is_state('sensor.upstairs_smoke_alarm_alarm_type', '1') }}
    upstairs_co_detected:
      friendly_name: Upstairs CO Detected
      device_class: smoke
      value_template: >-
        {{ is_state('sensor.upstairs_smoke_alarm_alarm_level', '255') and is_state('sensor.upstairs_smoke_alarm_alarm_type', '2') }}
    upstairs_smoke_alarm_test:
      friendly_name: Upstairs Smoke Alarm Test
      device_class: smoke
      value_template: >-
        {{ is_state('sensor.upstairs_smoke_alarm_alarm_level', '0') and is_state('sensor.upstairs_smoke_alarm_alarm_type', '12') }}
    downstairs_smoke_detected:
      friendly_name: Downstairs Smoke Detected
      device_class: smoke
      value_template: >-
        {{ is_state('sensor.downstairs_smoke_alarm_alarm_level', '255') and is_state('sensor.downstairs_smoke_alarm_alarm_type', '1') }}
    downstairs_co_detected:
      friendly_name: Downstairs CO Detected
      device_class: smoke
      value_template: >-
        {{ is_state('sensor.downstairs_smoke_alarm_alarm_level', '255') and is_state('sensor.downstairs_smoke_alarm_alarm_type', '2') }}
    downstairs_smoke_alarm_test:
      friendly_name: Downstairs Smoke Alarm Test
      device_class: smoke
      value_template: >-
        {{ is_state('sensor.downstairs_smoke_alarm_alarm_level', '0') and is_state('sensor.downstairs_smoke_alarm_alarm_type', '12') }}
    family_room_smoke_detected:
      friendly_name: Family Room Smoke Detected
      device_class: smoke
      value_template: >-
        {{ is_state('sensor.family_room_smoke_alarm_alarm_level', '255') and is_state('sensor.family_room_smoke_alarm_alarm_type', '1') }}
    family_room_co_detected:
      friendly_name: Family Room CO Detected
      device_class: smoke
      value_template: >-
        {{ is_state('sensor.family_room_smoke_alarm_alarm_level', '255') and is_state('sensor.family_room_smoke_alarm_alarm_type', '2') }}
    family_room_smoke_alarm_test:
      friendly_name: Family Room Smoke Alarm Test
      device_class: smoke
      value_template: >-
        {{ is_state('sensor.family_room_smoke_alarm_alarm_level', '0') and is_state('sensor.family_room_smoke_alarm_alarm_type', '12') }}
