- id: '1497804129147'
  alias: House fan off below 80 degrees
  trigger:
  - below: '80'
    entity_id: sensor.ah02_th_temperature
    for: 00:02:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.aeotec_micro_switch_2nd_edition_switch
    state: 'on'
  action:
  - data:
      entity_id: fan.house_fan
    service: fan.turn_off
- id: '1500947016373'
  alias: Camera Motion and Floods On Armed Away
  trigger:
  - entity_id: alarm_control_panel.3629_alarm
    platform: state
    to: armed_away
  action:
  - data:
      entities: switch.foscam_cam1_motion
    service: switch.turn_on
  - data:
      entity_id: switch.foscam_cam2_motion
    service: switch.turn_on
  - data:
      entity_id: switch.foscam_cam3_motion
    service: switch.turn_on
  - data:
      entity_id: switch.generic_cam4_motion
    service: switch.turn_on
  - data:
      entity_id: light.l_6
    service: light.turn_on
- id: '1500947016399'
  alias: Camera Motion and Floods On Armed Night
  trigger:
  - entity_id: alarm_control_panel.3629_alarm
    platform: state
    to: armed_night
  action:
  - data:
      entity_id: switch.foscam_cam1_motion
    service: switch.turn_on
  - data:
      entity_id: switch.foscam_cam2_motion
    service: switch.turn_on
  - data:
      entity_id: light.l_6
    service: light.turn_on
- id: '1500947000000'
  alias: Camera Motion On Armed Home
  trigger:
  - entity_id: alarm_control_panel.3629_alarm
    platform: state
    to: armed_home
  action:
  - data:
      entity_id: switch.foscam_cam1_motion
    service: switch.turn_on
  - data:
      entity_id: switch.foscam_cam2_motion
    service: switch.turn_on
- id: '1500948466889'
  alias: Camera Motion and Floods Off Disarmed
  trigger:
  - entity_id: alarm_control_panel.3629_alarm
    platform: state
    to: disarmed
  action:
  - data:
      entity_id: switch.foscam_cam1_motion
    service: switch.turn_off
  - data:
      entity_id: switch.foscam_cam2_motion
    service: switch.turn_off
  - data:
      entity_id: switch.foscam_cam3_motion
    service: switch.turn_off
  - data:
      entity_id: switch.generic_cam4_motion
    service: switch.turn_off
  - data:
      entity_id: light.l_6
    service: light.turn_off
- id: '1800999911110'
  alias: 3629cam4 Up
  trigger:
  - below: '-0.1'
    entity_id: input_number.cam4_up_down
    platform: numeric_state
  action:
  - data:
      entity_id: switch.generic_cam4_up
    service: homeassistant.turn_on
- id: '1800999911111'
  alias: 3629cam4 Up Down Stop
  trigger:
  - above: '-0.1'
    below: '0.1'
    entity_id: input_number.cam4_up_down
    platform: numeric_state
  action:
  - data:
      entity_id: switch.generic_cam4_up
    service: homeassistant.turn_off
  - data:
      entity_id: switch.generic_cam4_down
    service: homeassistant.turn_off
- id: '1800999911112'
  alias: 3629cam4 Down
  trigger:
  - above: '0.1'
    entity_id: input_number.cam4_up_down
    platform: numeric_state
  action:
  - data:
      entity_id: switch.generic_cam4_down
    service: homeassistant.turn_on
- id: '1800999911113'
  alias: 3629cam4 Left
  trigger:
  - below: '-0.1'
    entity_id: input_number.cam4_left_right
    platform: numeric_state
  action:
  - data:
      entity_id: switch.generic_cam4_left
    service: homeassistant.turn_on
- id: '1800999911114'
  alias: 3629cam4 Left Right Stop
  trigger:
  - above: '-0.1'
    below: '0.1'
    entity_id: input_number.cam4_left_right
    platform: numeric_state
  action:
  - data:
      entity_id: switch.generic_cam4_left
    service: homeassistant.turn_off
  - data:
      entity_id: switch.generic_cam4_right
    service: homeassistant.turn_off
- id: '1800999911115'
  alias: 3629cam4 Right
  trigger:
  - above: '0.1'
    entity_id: input_number.cam4_left_right
    platform: numeric_state
  action:
  - data:
      entity_id: switch.generic_cam4_right
    service: homeassistant.turn_on
- id: '1533419985023'
  alias: Irrigation Run
  trigger:
  - at: 06:30:00
    platform: time
  condition:
  - condition: state
    entity_id: switch.nm14_rly4_4
    state: 'on'
  action:
  - data:
      entity_id: switch.nm14_rly4_1
    service: switch.turn_on
  - delay: '{{ states(''input_number.zone1_run_minutes'') | multiply(60) | timestamp_custom(''%H:%M:%S'',False)
      }}'
  - data:
      entity_id: switch.nm14_rly4_1
    service: switch.turn_off
  - data:
      entity_id: switch.nm14_rly4_3
    service: switch.turn_on
  - delay: '{{ states(''input_number.zone3_run_minutes'') | multiply(60) | timestamp_custom(''%H:%M:%S'',False)
      }}'
  - data:
      entity_id: switch.nm14_rly4_3
    service: switch.turn_off
- id: '1545515732471'
  alias: Floods on at 11:00 PM
  trigger:
  - at: '23:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.l_6
    service: light.turn_on
- id: '1545515874358'
  alias: Floods off at 04:30 AM
  trigger:
  - at: 04:30
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.l_6
    service: light.turn_off
- id: '1548612260526'
  alias: Irrigation Enable
  trigger:
  - platform: template
    value_template: '{{ now().month > 4 and now().month < 9 and (''rain'' not in states.sensor.dark_sky_hourly_summary.state
      and ''Rain'' not in states.sensor.dark_sky_hourly_summary.state) }}'
  condition: []
  action:
  - data:
      entity_id: switch.nm14_rly4_4
    service: switch.turn_on
- id: '1548612882816'
  alias: Irrigation Disable
  trigger:
  - platform: template
    value_template: '{{ (now().month <= 4 or now().month >=9) or not (''rain'' in
      states.sensor.dark_sky_hourly_summary.state or ''Rain'' in states.sensor.dark_sky_hourly_summary.state)
      }}'
  condition: []
  action:
  - data:
      entity_id: switch.nm14_rly4_4
    service: switch.turn_off
- id: '1548861516503'
  alias: Reboot Wink Weekly
  trigger:
  - platform: template
    value_template: '{{ now().weekday() == 0 }}'
  - at: 02:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sb03_relay
    service: homeassistant.turn_off
  - delay: 00:01
  - data:
      entity_id: switch.sb03_relay
    service: homeassistant.turn_on
- id: '1548862723503'
  alias: Power On Wink
  trigger:
  - entity_id: switch.sb03_relay
    for: 00:02
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.sb03_relay
    service: homeassistant.turn_on
- id: '1552222922150'
  alias: Open Blinds at Dawn
  trigger:
  - event: sunrise
    offset: -00:20:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.nm01_sv1_cover
    service: cover.open_cover_tilt
  - data:
      entity_id: cover.nm02_sv1_cover
    service: cover.open_cover_tilt
  - data:
      entity_id: cover.nm03_sv1_cover
    service: cover.open_cover_tilt
  - data:
      entity_id: cover.nm04_sv1_cover
    service: cover.open_cover_tilt
  - data:
      entity_id: cover.nm05_sv1_cover
    service: cover.open_cover_tilt
- id: '1552245394001'
  alias: Close Blinds at 11:00 PM
  trigger:
  - at: '23:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: cover.nm01_sv1_cover
    service: cover.close_cover_tilt
  - data:
      entity_id: cover.nm02_sv1_cover
    service: cover.close_cover_tilt
  - data:
      entity_id: cover.nm03_sv1_cover
    service: cover.close_cover_tilt
  - data:
      entity_id: cover.nm04_sv1_cover
    service: cover.close_cover_tilt
  - data:
      entity_id: cover.nm05_sv1_cover
    service: cover.close_cover_tilt
- id: '1552938556370'
  alias: Grow Lamp on at 06:00 AM
  trigger:
  - at: 06:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sb04_relay
    service: switch.turn_on
- id: '1552938778764'
  alias: Grow Lamp off at 08:00 PM
  trigger:
  - at: '20:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sb04_relay
    service: switch.turn_off
- id: '1560461893289'
  alias: Security Lighting On Close Blinds
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: alarm_control_panel.3629_alarm
    state: armed_away
  action:
  - data: {}
    service: script.1560462776632
  - data: {}
    service: script.1571453541250
- id: '1560462571547'
  alias: Security Lighting Off
  trigger:
  - at: '21:37'
    platform: time
  condition:
  - condition: state
    entity_id: alarm_control_panel.3629_alarm
    state: armed_away
  action:
  - delay: 00:{{ (range(5, 25) | random) }}:00
  - service: script.1560463039446
- id: '1562957476111'
  alias: Master Bedroom Ceiling Fan Remote Stop
  trigger:
  - entity_id: binary_sensor.nm06_rfx1_fan_remote_stop
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: ' fan.ge_unknown_type_4944_id_3131_level'
    service: fan.turn_off
- id: '1562957684896'
  alias: Master Bedroom Ceiling Fan Remote Hi
  trigger:
  - entity_id: binary_sensor.nm06_rfx1_fan_remote_hi
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: ' fan.ge_unknown_type_4944_id_3131_level'
      speed: high
    service: fan.set_speed
- id: '1562958033989'
  alias: Master Bedroom Ceiling Fan Remote Medium
  trigger:
  - entity_id: binary_sensor.nm06_rfx1_fan_remote_med
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: ' fan.ge_unknown_type_4944_id_3131_level'
      speed: medium
    service: fan.set_speed
- id: '1562958094562'
  alias: Master Bedroom Ceiling Fan Remote Low
  trigger:
  - entity_id: binary_sensor.nm06_rfx1_fan_remote_low
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: ' fan.ge_unknown_type_4944_id_3131_level'
      speed: low
    service: fan.set_speed
- id: '1563648409962'
  alias: Arm Night
  trigger:
  - at: '23:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: state
    entity_id: alarm_control_panel.3629_alarm
    state: disarmed
  action:
  - data:
      entity_id: all
    service: alarm_control_panel.alarm_arm_night
- id: '1563648489927'
  alias: Disarm Home Morning
  trigger:
  - at: 06:00:00
    platform: time
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: state
    entity_id: alarm_control_panel.3629_alarm
    state: armed_night
  action:
  - data:
      entity_id: all
    service: alarm_control_panel.alarm_disarm
- id: '1563648590512'
  alias: Arm Away
  trigger:
  - entity_id: group.family
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: all
    service: alarm_control_panel.alarm_arm_away
- id: '1563648678608'
  alias: Disarm Return Home
  trigger:
  - entity_id: group.family
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: all
    service: alarm_control_panel.alarm_disarm
- id: '1572629564877'
  alias: Security Notify Front Door Opened
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door
    for: 00:01:00
    platform: state
    to: open
  condition:
  - condition: state
    entity_id: alarm_control_panel.3629_alarm
    state: armed_away
  action:
  - data:
      message: The front door has been open for more than one minute
      title: Front Door Opened
    service: notify.notify
- id: '1572629774481'
  alias: Security Notify Back Door Opened
  description: ''
  trigger:
  - entity_id: binary_sensor.back_door
    for: 00:01:00
    platform: state
    to: open
  condition:
  - condition: state
    entity_id: alarm_control_panel.3629_alarm
    state: armed_away
  action:
  - data:
      message: The back door has been open for more than one minute
      title: Back Door Opened
    service: notify.notify
- id: '1572629944102'
  alias: Security Notify Garage Door Opened
  description: ''
  trigger:
  - entity_id: binary_sensor.garage_door
    platform: state
    to: open
  condition:
  - condition: state
    entity_id: alarm_control_panel.3629_alarm
    state: armed_away
  action:
  - data:
      message: The garage door has been open for more than one minute
      title: Garage Door Opened
    service: notify.notify
- id: '1572630307272'
  alias: Security Notify Family Room Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.family_room_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.3629_alarm
    state: armed_away
  action:
  - data:
      message: Motion has been detected in the Family Room
      title: Family Room Motion Detected
    service: notify.notify
- id: '1572630414451'
  alias: Security Notify Master Bedrom Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.master_bedroom_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.3629_alarm
    state: armed_away
  action:
  - data:
      message: Motion has been detected in the Master Bedroom
      title: Master Bedroom Motion Detected
    service: notify.notify
- id: '1572631200037'
  alias: Office Temperature Low
  description: ''
  trigger:
  - below: '50.0'
    entity_id: sensor.ah03_th_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      message: The temperature in the office is below 50 degrees
      title: Office Temperature Low
    service: notify.notify
- id: '1572633741649'
  alias: UPS Notify Offline
  description: ''
  trigger:
  - entity_id: binary_sensor.ups_online_status
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: The UPS has gone OFFLINE
      title: UPS OFFLINE
    service: notify.notify
- id: '1572633832196'
  alias: UPS Status Online
  description: ''
  trigger:
  - entity_id: binary_sensor.ups_online_status
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: The UPS has come back ONLINE
      title: UPS ONINE
    service: notify.notify
- id: '1576173820669'
  alias: Bird bath heater off at sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: switch.l_5
    state: 'on'
  action:
  - alias: ''
    data: {}
    entity_id: switch.l_5
    service: switch.turn_off
- id: '1576174004779'
  alias: Bird bath heater off above 32 degrees
  description: ''
  trigger:
  - above: '32'
    entity_id: sensor.dark_sky_temperature
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.l_5
    state: 'on'
  action:
  - data: {}
    entity_id: switch.l_5
    service: switch.turn_off
- id: '1576174236299'
  alias: Bird bath heater on below freezing daytime
  description: ''
  trigger:
  - below: '32'
    entity_id: sensor.dark_sky_temperature
    platform: numeric_state
  condition:
  - after: sunrise
    before: sunset
    condition: sun
  - condition: state
    entity_id: switch.l_5
    state: 'off'
  action:
  - data: {}
    entity_id: switch.l_5
    service: switch.turn_on
- id: '1576243291952'
  alias: Bird bath heater on at sunrise below freezing
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition:
  - below: '32'
    condition: numeric_state
    entity_id: sensor.dark_sky_temperature
  action:
  - entity_id: switch.l_5
    service: switch.turn_on
- id: '1578535843455'
  alias: Garage latch off when door open
  description: ''
  trigger:
  - entity_id: binary_sensor.garage_door
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: switch.nm08_sv1_latch_servo
    service: switch.turn_off
- id: '1578620613401'
  alias: Humidifier off above set point
  description: ''
  trigger:
  - above: '0'
    entity_id: sensor.ah02_th_humidity
    platform: numeric_state
    value_template: '{{ states(''sensor.ah02_th_humidity'') | float - states(''input_number.humidifier_off'')
      | float }}'
  condition: []
  action:
  - entity_id: switch.sb05_relay
    service: switch.turn_off
- id: '1578620814432'
  alias: Humidifier on below set point
  description: ''
  trigger:
  - below: '0'
    entity_id: sensor.ah02_th_humidity
    platform: numeric_state
    value_template: '{{ states(''sensor.ah02_th_humidity'') | float - states(''input_number.humidifier_on'')
      | float }}'
  condition: []
  action:
  - entity_id: switch.sb05_relay
    service: switch.turn_on
