homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  # Pick yours from here - http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # imperial for US units
  unit_system: imperial

  # add this part
  auth_providers:
   - type: homeassistant
   # uncomment this to enable backwards compatible API password support
   - type: legacy_api_password
     api_password: !secret http_password

  customize: !include customize.yaml

# Logger setup
logger:
  default: warning
  logs:
    homeassistant.components.mqtt.cover: debug

system_health:

person:

default_config:

# Sensor to tell the current available release
sensor v:
  - platform: version
    source: pypi

# Track the sun
sun:

# Make date available for automations
sensor d:
  - platform: time_date
    display_options:
      - 'date'

# View all events in a logbook
logbook:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# Enables support for tracking state changes over time.
recorder:
  purge_interval: 1
  purge_keep_days: 14
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - automation
    entities:
      - sun.sun # Don't record sun data
      - persistent_notification.invalid_config
      - sensor.date

  # Delete events and states older than 4 weeks
#  purge_days: 28

# Allows you to issue voice commands from the frontend
conversation:

# Show links to resources in log and frontend
introduction:

# Discover some devices automatically
discovery:

# In case discovery fails to find the Chromecasts
#media_player:
#  - platform: cast

# NEW configuration panels
config:

# NEW automation configuration panels
automation: !include automations.yaml

# NEW script editor
script: !include scripts.yaml

# Cloud connectivity
cloud:
  google_actions:
    filter:
      exclude_entities:
        - climate.thermostat
        - light.bedside_light_bulb
        - light.garage_attic
        - light.guest_room_link_bulb
        - light.family_room_link_bulb_1
        - light.family_room_link_bulb_2
        - light.dining_room_light
        - light.computer_light_bulb
        - light.family_room_nw_ceiling_light
        - light.family_room_se_ceiling_light
        - switch.living_room_lamp_outlet
        - switch.smart_plug_isp6x
        - switch.house_fan_switch
        - switch.desert_front_porch_camera
        - switch.desert_living_room_camera
        - switch.generic_cam4_down
        - switch.generic_cam4_left
        - switch.generic_cam4_right
        - switch.generic_cam4_up
        - group.michael
        - group.susan
        - group.family
        - group.all_switches
        - media_player.mini
        - media_player.bedroom_tv

# Security
http:
#  api_password: !secret http_password
#  base_url: https://mtl-svn.dyndns-home.com:8123
#  ssl_certificate: /home/homeassistant/ssl/fullchain.pem
#  ssl_key: /home/homeassistant/ssl/privkey.pem

# Wink (only works with dev OAuth now)
#wink: !include wink.yaml
wink:
  local_control: true

# Device tracking
device_tracker: !include nmap_tracker.yaml

# Honeywell Thermostat
climate: !include climate.yaml

# X10 over Heyu "hub"
heyu: !include heyu.yaml

# X10 Lights over Heyu
light x: !include heyu_light.yaml

# X10 Switches over Heyu
switch x: !include heyu_switch.yaml

# DarkSky sensor
sensor w: !include darksky_sensor.yaml

# DarkSky weather
weather: !include darksky_weather.yaml

# Groups (all in customize now)
group: !include groups.yaml

# MQTT
mqtt:
  broker: !secret mqtt_broker
  client_id: !secret mqtt_client_id
  password: !secret mqtt_password
  discovery: true
  protocol: 3.1

# Temperature sensor over MQTT
#sensor 2: !include mqtt_temp1.yaml

# Humidity sensor over MQTT
#sensor 3: !include mqtt_hum1.yaml

# Barometer sensor over MQTT
#sensor 4: !include mqtt_baro1.yaml

# Temperature sensor over MQTT
#sensor 5: !include mqtt_temp2.yaml

# Humidity sensor over MQTT
#sensor 6: !include mqtt_hum2.yaml

# DTE Energy Bridge
#sensor 7: !include energy_bridge.yaml

# Relay 1-1 over MQTT
#switch 1: !include mqtt_relay11.yaml

# Relay 1-2 over MQTT
#switch 2: !include mqtt_relay12.yaml

# Relay 1-3 over MQTT
#switch 3: !include mqtt_relay13.yaml

# Relay 1-4 over MQTT
#switch 4: !include mqtt_relay14.yaml

# IFTTT channel using Maker
ifttt: !include ifttt.yaml

# APC UPS Daemon
apcupsd:
sensor u: !include apcupsd.yaml

# USPS (broke again)
#usps: !include usps.yaml

# UPS (deactivating to avoid future problems)
#sensor 10: !include ups.yaml

# FedEx (broke too now)
#sensor 11: !include fedex.yaml

# Temperature Probe over MQTT
#sensor 31: !include mqtt_temp3_1.yaml

# Temperature Probe over MQTT
#sensor 32: !include mqtt_temp3_2.yaml

# Temperature Probe over MQTT
#sensor 33: !include mqtt_temp3_3.yaml

# Temperature Probe over MQTT
#sensor 34: !include mqtt_temp3_4.yaml

# Temperature sensor over MQTT
#sensor 16: !include mqtt_temp4.yaml

# Humidity sensor over MQTT
#sensor 17: !include mqtt_hum4.yaml

# USB Camera
#camera: !include camera.yaml

# Weblinks for cameras
weblink: !include weblinks.yaml

# Foscam IP Camera 1
camera c1: !include foscam_cam1.yaml
switch c1: !include foscam_cam1_switch.yaml

# Foscam IP Camera 2
camera c2: !include foscam_cam2.yaml
switch c2: !include foscam_cam2_switch.yaml

# Foscam IP Camera 3
camera c3: !include foscam_cam3.yaml
switch c3: !include foscam_cam3_switch.yaml

# Alarm panel
alarm_control_panel: !include alarm_panel.yaml

# Nest Stuff
nest: !include nest.yaml

# Desert Front Porch Camera Control
switch df: !include desert_front_porch_camera_switch.yaml

# Desert Living Room Camera Control
switch dl: !include desert_living_room_camera_switch.yaml

# ZWave
#zwave:
#  device_config: !include zwave_device_config.yaml

# Generic iSmart IP camera
camera c4: !include generic_cam4.yaml
switch c4a: !include generic_cam4_switch_ptz.yaml
switch c4b: !include generic_cam4_switch_motion.yaml
input_number: !include generic_cam4_slider_ptz.yaml

sensor baro: !include corrected_barometer.yaml
sensor tpf: !include temp_probes_1-4_F.yaml

sensor sys: !include systemmonitor.yaml

sensor cover: !include mqtt_cover_sensors.yaml

