homeassistant:
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Required http setup for reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24  # Add the IP address of the proxy server
    
# Discover some devices automatically
discovery:

# Logger setup
logger: !include logger.yaml
system_log:
  fire_event: true

# Enables support for tracking state changes over time.
recorder: !include recorder.yaml

# Various manually defined devices
# Alarm panel
alarm_control_panel: !include alarm_control_panel.yaml

binary_sensor: !include_dir_merge_list binary_sensor

camera: !include_dir_merge_list camera

# Generic Thermostat for attic fan
climate: !include_dir_merge_list climate

# Device tracking
device_tracker: !include device_tracker.yaml

generic_hygrostat: !include generic_hygrostat.yaml

mqtt: !include mqtt.yaml

# Hangouts Notifications
notify: !include notify.yaml

sensor: !include_dir_merge_list sensor

shell_command: !include shell_command.yaml

switch: !include_dir_merge_list switch

template: !include_dir_merge_list template

