homeassistant:
  customize: !include customize.yaml

default_config:
# Stuff that is included by default_config:
automation: !include automations.yaml
#cloud:
#config:
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
history: !include history.yaml
#logbook:
#map:
#mobile_app:
#person:
script: !include scripts.yaml
#ssdp:
#sun:
#system_health:
#updater:
#zeroconf:

# APC UPS Daemon
apcupsd:

# Allows you to issue voice commands from the frontend
conversation:

# Discover some devices automatically
discovery:

#Google Calendar
google: !include google.yaml

# Groups (all in customize now)
group: !include groups.yaml

# X10 over Heyu "hub"
heyu: !include heyu.yaml

# Security
http:

# IFTTT channel using Maker
ifttt: !include ifttt.yaml

# Logger setup
logger: !include logger.yaml

# Manual integrations
# MQTT
mqtt: !include mqtt.yaml

# Nest Stuff
nest: !include nest.yaml

# Enables support for tracking state changes over time.
recorder: !include recorder.yaml

# Scenes in directory
scene: !include scenes.yaml

# NEW streaming support
stream:

# Wink
wink: !include wink.yaml

# ZWave
zwave: !include zwave.yaml

# Various manually defined devices
# Alarm panel
alarm_control_panel: !include alarm_control_panel.yaml

binary_sensor: !include_dir_merge_list binary_sensor

camera: !include_dir_merge_list camera

# Honeywell Thermostat
climate: !include climate.yaml

# Device tracking
device_tracker: !include device_tracker.yaml

fan: !include_dir_merge_list fan

# HDHomeRun integration in HACS
hdhomerun:

input_number: !include_dir_merge_named input_number

light: !include_dir_merge_list light

# HTML5 Push Notifications
notify: !include notify.yaml

sensor: !include_dir_merge_list sensor

switch: !include_dir_merge_list switch

# DarkSky weather
weather: !include_dir_merge_list weather

# Weblinks for cameras
weblink: !include weblinks.yaml


