homeassistant:
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
#tts:
#  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#history: !include history.yaml
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes


# Allows you to issue voice commands from the frontend
#conversation:

# Discover some devices automatically
discovery:

#Google Calendar
google: !include google.yaml

# X10 over Heyu "hub"
#heyu: !include heyu.yaml

# IFTTT channel using Maker
#ifttt: !include ifttt.yaml

# Logger setup
logger: !include logger.yaml

# Nest Stuff
nest: !include nest.yaml

# Enables support for tracking state changes over time.
recorder: !include recorder.yaml

# NEW streaming support
stream:

# Wink
wink: !include wink.yaml

# Various manually defined devices
# Alarm panel
alarm_control_panel: !include alarm_control_panel.yaml

binary_sensor: !include_dir_merge_list binary_sensor

camera: !include_dir_merge_list camera

# Honeywell Thermostat
climate: !include climate.yaml

# Cover groups
cover: !include cover.yaml

# Device tracking
device_tracker: !include device_tracker.yaml

fan: !include_dir_merge_list fan

# HDHomeRun integration in HACS
#hdhomerun:

# HTML5 Push Notifications
notify: !include notify.yaml

sensor: !include_dir_merge_list sensor

switch: !include_dir_merge_list switch

# Weather
#weather: !include_dir_merge_list weather


