homeassistant:
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#history: !include history.yaml

# Discover some devices automatically
discovery:

#Google Calendar
google: !include google.yaml

# Logger setup
logger: !include logger.yaml

# Enables support for tracking state changes over time.
recorder: !include recorder.yaml

# NEW streaming support
stream:

# Various manually defined devices
# Alarm panel
alarm_control_panel: !include alarm_control_panel.yaml

binary_sensor: !include_dir_merge_list binary_sensor

camera: !include_dir_merge_list camera

# Honeywell Thermostat
climate: !include_dir_merge_list climate

# Cover groups
cover: !include cover.yaml

# Device tracking
device_tracker: !include device_tracker.yaml

fan: !include_dir_merge_list fan

light: !include_dir_merge_list light

# Hangouts Notifications
notify: !include notify.yaml

number: !include_dir_merge_list number

sensor: !include_dir_merge_list sensor

switch: !include_dir_merge_list switch

