- platform: template
  sensors:
    corrected_barometer:
      friendly_name: "Corrected Barometer"
      unit_of_measurement: 'hPa'
      value_template: "{{ (states('sensor.ah01_tph_pressure') | float + 34.0) | round(1) }}"
      icon_template: "mdi:gauge"
    corrected_barometer_inhg:
      friendly_name: "Corrected Barometer (inHg)"
      unit_of_measurement: 'inHg'
      value_template: "{{ ((states('sensor.ah01_tph_pressure') | float + 34.0) * 0.0295) | round(2) }}"
      icon_template: "mdi:gauge"
