- platform: group
  name: "Living Room Blinds"
  unique_id: living_room_blinds
  entities:
    - cover.living_room_se_blinds
    - cover.living_room_se_ctr_blinds
    - cover.living_room_ctr_blinds
    - cover.living_room_nw_ctr_blinds
    - cover.living_room_nw_blinds
- platform: group
  name: "Family Room Blinds"
  unique_id: family_room_blinds
  entities:
    - cover.family_room_sene_blinds
    - cover.family_room_sesw_blinds
    - cover.family_room_swse_blinds
    - cover.family_room_swnw_blinds
    - cover.family_room_nwsw_blinds
    - cover.family_room_nwne_blinds
- platform: group
  name: "Family Room SE Blinds"
  unique_id: family_room_se_blinds
  entities:
    - cover.family_room_sene_blinds
    - cover.family_room_sesw_blinds
- platform: group
  name: "Family Room SW Blinds"
  unique_id: family_room_sw_blinds
  entities:
    - cover.family_room_swse_blinds
    - cover.family_room_swnw_blinds
- platform: group
  name: "Family Room NW Blinds"
  unique_id: family_room_nw_blinds
  entities:
    - cover.family_room_nwsw_blinds
    - cover.family_room_nwne_blinds
