- platform: group
  name: "Living Room Blinds"
  entities:
    - cover.living_room_se_blinds
    - cover.living_room_se_ctr_blinds
    - cover.living_room_ctr_blinds
    - cover.living_room_nw_ctr_blinds
    - cover.living_room_nw_blinds