- platform: mqtt
  name: "NM04_SV1 Cover"
  state_topic: nm04_sv1/cover/nm04_sv1_cover/state
  tilt_command_topic: nm04_sv1/cover/nm04_sv1_cover/tilt/command
  tilt_status_topic: nm04_sv1/cover/nm04_sv1_cover/tilt/state
  tilt_min: 0
  tilt_max: 100
  tilt_closed_value: 5
  tilt_opened_value: 45

