- platform: template
  fans:
    house_fan:
      friendly_name: "House Fan"
      value_template: "{{ states('switch.aeotec_micro_switch_2nd_edition_switch') }}"
      speed_template: "{{ 'medium' }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.aeotec_micro_switch_2nd_edition_switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.aeotec_micro_switch_2nd_edition_switch
      set_speed:
        service: switch.turn_on
        data:
          entity_id: switch.aeotec_micro_switch_2nd_edition_switch

