- platform: template
  switches: 
    3629cam5_left:
      unique_id: 3629cam5_left
      friendly_name: "3629 Cam 5 Left"
      icon_template: "mdi:arrow-left-bold"
      value_template: > 
        {% if is_state('switch.3629cam5_left','on') %}
          false
        {% endif %}
      turn_on:
        service: amcrest.ptz_control
        data:
          entity_id: camera.3629_cam_5
          movement: left
          travel_time: 0.05
      turn_off:
    3629cam5_right:
      unique_id: 3629cam5_right
      friendly_name: "3629 Cam 5 Right"
      icon_template: "mdi:arrow-right-bold"
      value_template: > 
        {% if is_state('switch.3629cam5_right','on') %}
          false
        {% endif %}
      turn_on:
        service: amcrest.ptz_control
        data:
          entity_id: camera.3629_cam_5
          movement: right
          travel_time: 0.05
      turn_off:
    3629cam5_up:
      unique_id: 3629cam5_up
      friendly_name: "3629 Cam 5 Up"
      icon_template: "mdi:arrow-up-bold"
      value_template: > 
        {% if is_state('switch.3629cam5_up','on') %}
          false
        {% endif %}
      turn_on:
        service: amcrest.ptz_control
        data:
          entity_id: camera.3629_cam_5
          movement: up
          travel_time: 0.05
      turn_off:
    3629cam5_down:
      unique_id: 3629cam5_down
      friendly_name: "3629 Cam 5 Down"
      icon_template: "mdi:arrow-down-bold"
      value_template: > 
        {% if is_state('switch.3629cam5_down','on') %}
          false
        {% endif %}
      turn_on:
        service: amcrest.ptz_control
        data:
          entity_id: camera.3629_cam_5
          movement: down
          travel_time: 0.05
      turn_off:
    3629cam5_call_pos_1:
      unique_id: 3629cam5_call_pos_1
      friendly_name: "3629 Cam 5 Call Position 1"
      icon_template: "mdi:numeric-1-box-outline"
      value_template: > 
        {% if is_state('switch.3629cam5_call_pos_1','on') %}
          false
        {% endif %}
      turn_on:
        service: amcrest.goto_preset
        data:
          entity_id: camera.3629_cam_5
          preset: 1
      turn_off:
    3629cam5_call_pos_2:
      unique_id: 3629cam5_call_pos_2
      friendly_name: "3629 Cam 5 Call Position 2"
      icon_template: "mdi:numeric-2-box-outline"
      value_template: > 
        {% if is_state('switch.3629cam5_call_pos_2','on') %}
          false
        {% endif %}
      turn_on:
        service: amcrest.goto_preset
        data:
          entity_id: camera.3629_cam_5
          preset: 2
      turn_off:
    3629cam5_call_pos_3:
      unique_id: 3629cam5_call_pos_3
      friendly_name: "3629 Cam 5 Call Position 3"
      icon_template: "mdi:numeric-3-box-outline"
      value_template: > 
        {% if is_state('switch.3629cam5_call_pos_3','on') %}
          false
        {% endif %}
      turn_on:
        service: amcrest.goto_preset
        data:
          entity_id: camera.3629_cam_5
          preset: 3
      turn_off:
    3629cam5_call_pos_4:
      unique_id: 3629cam5_call_pos_4
      friendly_name: "3629 Cam 5 Call Position 4"
      icon_template: "mdi:numeric-4-box-outline"
      value_template: > 
        {% if is_state('switch.3629cam5_call_pos_4','on') %}
          false
        {% endif %}
      turn_on:
        service: amcrest.goto_preset
        data:
          entity_id: camera.3629_cam_5
          preset: 4
      turn_off: