- platform: template
  switches: 
    3629cam6_left:
      unique_id: 3629cam6_left
      friendly_name: "3629 Cam 6 Left"
      icon_template: "mdi:arrow-left-bold"
      value_template: > 
        {% if is_state('switch.3629cam6_left','on') %}
          false
        {% endif %}
      turn_on:
        service: onvif.ptz
        data:
          continuous_duration: 0.1
          move_mode: ContinuousMove
          pan: "LEFT"
        target:
          entity_id: camera.3629_cam_6_mainstreamprofile
      turn_off:
    3629cam6_right:
      unique_id: 3629cam6_right
      friendly_name: "3629 Cam 6 Right"
      icon_template: "mdi:arrow-right-bold"
      value_template: > 
        {% if is_state('switch.3629cam6_right','on') %}
          false
        {% endif %}
      turn_on:
        service: onvif.ptz
        data:
          continuous_duration: 0.1
          move_mode: ContinuousMove
          pan: "RIGHT"
        target:
          entity_id: camera.3629_cam_6_mainstreamprofile
      turn_off:
    3629cam6_up:
      unique_id: 3629cam6_up
      friendly_name: "3629 Cam 6 Up"
      icon_template: "mdi:arrow-up-bold"
      value_template: > 
        {% if is_state('switch.3629cam6_up','on') %}
          false
        {% endif %}
      turn_on:
        service: onvif.ptz
        data:
          continuous_duration: 0.1
          move_mode: ContinuousMove
          tilt: "UP"
        target:
          entity_id: camera.3629_cam_6_mainstreamprofile
      turn_off:
    3629cam6_down:
      unique_id: 3629cam6_down
      friendly_name: "3629 Cam 6 Down"
      icon_template: "mdi:arrow-down-bold"
      value_template: > 
        {% if is_state('switch.3629cam6_down','on') %}
          false
        {% endif %}
      turn_on:
        service: onvif.ptz
        data:
          continuous_duration: 0.1
          move_mode: ContinuousMove
          tilt: "DOWN"
        target:
          entity_id: camera.3629_cam_6_mainstreamprofile
      turn_off:
    3629cam6_call_pos_1:
      unique_id: 3629cam6_call_pos_1
      friendly_name: "3629 Cam 6 Call Position 1"
      icon_template: "mdi:numeric-1-box-outline"
      value_template: > 
        {% if is_state('switch.3629cam6_call_pos_1','on') %}
          false
        {% endif %}
      turn_on:
        service: onvif.ptz
        data:
          move_mode: GotoPreset
          preset: "Preset001"
        target:
          entity_id: camera.3629_cam_6_mainstreamprofile
      turn_off:
    3629cam6_call_pos_2:
      unique_id: 3629cam6_call_pos_2
      friendly_name: "3629 Cam 6 Call Position 2"
      icon_template: "mdi:numeric-2-box-outline"
      value_template: > 
        {% if is_state('switch.3629cam6_call_pos_2','on') %}
          false
        {% endif %}
      turn_on:
        service: onvif.ptz
        data:
          move_mode: GotoPreset
          preset: "Preset002"
        target:
          entity_id: camera.3629_cam_6_mainstreamprofile
      turn_off:
    3629cam6_call_pos_3:
      unique_id: 3629cam6_call_pos_3
      friendly_name: "3629 Cam 6 Call Position 3"
      icon_template: "mdi:numeric-3-box-outline"
      value_template: > 
        {% if is_state('switch.3629cam6_call_pos_3','on') %}
          false
        {% endif %}
      turn_on:
        service: onvif.ptz
        data:
          move_mode: GotoPreset
          preset: "Preset003"
        target:
          entity_id: camera.3629_cam_6_mainstreamprofile
      turn_off:
    3629cam6_call_pos_4:
      unique_id: 3629cam6_call_pos_4
      friendly_name: "3629 Cam 6 Call Position 4"
      icon_template: "mdi:numeric-4-box-outline"
      value_template: > 
        {% if is_state('switch.3629cam6_call_pos_4','on') %}
          false
        {% endif %}
      turn_on:
        service: onvif.ptz
        data:
          move_mode: GotoPreset
          preset: "Preset004"
        target:
          entity_id: camera.3629_cam_6_mainstreamprofile
      turn_off: