# Replace admin and password with an "Admin" privileged Foscam user
# Replace ipaddress with the local IP address of your Foscam
- platform: command_line
  switches:
    #Switch for Foscam Motion Detection
    foscam_cam2_motion:
      friendly_name: "3629Cam2 Motion Enable"
      icon_template: mdi:run
      command_on: '/config/scripts/c2.sh on'
      command_off: '/config/scripts/c2.sh off'
      command_state: '/config/scripts/c2.sh'
      value_template: '{{ value == "1" }}'


