- platform: command_line
  switches:
    #Switch for iSmart PTZ up
    generic_cam4_up:
      friendly_name: "3629Cam4 PTZ Up"
      command_on: '/home/homeassistant/.homeassistant/scripts/c4_ptz.sh on up'
      command_off: '/home/homeassistant/.homeassistant/scripts/c4_ptz.sh off up'
    #Switch for iSmart PTZ down
    generic_cam4_down:
      friendly_name: "3629Cam4 PTZ Down"
      command_on: '/home/homeassistant/.homeassistant/scripts/c4_ptz.sh on down'
      command_off: '/home/homeassistant/.homeassistant/scripts/c4_ptz.sh off down'
    #Switch for iSmart PTZ left
    generic_cam4_left:
      friendly_name: "3629Cam4 PTZ Left"
      command_on: '/home/homeassistant/.homeassistant/scripts/c4_ptz.sh on left'
      command_off: '/home/homeassistant/.homeassistant/scripts/c4_ptz.sh off left'
    #Switch for iSmart PTZ right
    generic_cam4_right:
      friendly_name: "3629Cam4 PTZ Right"
      command_on: '/home/homeassistant/.homeassistant/scripts/c4_ptz.sh on right'
      command_off: '/home/homeassistant/.homeassistant/scripts/c4_ptz.sh off right'


