- platform: foscam
  #platform: generic
  name: "3629 Cam 1"
  username: !secret foscam1_username
  password: !secret foscam1_password
  ip: !secret foscam1_ip
  #still_image_url: !secret foscam1_still_url
  #stream_source: !secret foscam1_stream
  #verify_ssl: false

