- platform: template
  sensors:
    family_room_sene_blinds_tilt_position:
      friendly_name: "Family Room SE-NE Blinds Tilt Position"
      value_template: "{{ state_attr('cover.family_room_sene_blinds', 'current_tilt_position') }}"
    family_room_sesw_blinds_tilt_position:
      friendly_name: "Family Room SE-SW Blinds Tilt Position"
      value_template: "{{ state_attr('cover.family_room_sesw_blinds', 'current_tilt_position') }}"
    family_room_swse_blinds_tilt_position:
      friendly_name: "Family Room SW-SE Blinds Tilt Position"
      value_template: "{{ state_attr('cover.family_room_swse_blinds', 'current_tilt_position') }}"
    family_room_swnw_blinds_tilt_position:
      friendly_name: "Family Room SW-NW Blinds Tilt Position"
      value_template: "{{ state_attr('cover.family_room_swnw_blinds', 'current_tilt_position') }}"
    family_room_nwsw_blinds_tilt_position:
      friendly_name: "Family Room NW-SW Blinds Tilt Position"
      value_template: "{{ state_attr('cover.family_room_nwsw_blinds', 'current_tilt_position') }}"
    living_room_se_blinds_tilt_position:
      friendly_name: "Living Room SE Blinds Tilt Position"
      value_template: "{{ state_attr('cover.living_room_se_blinds', 'current_tilt_position') }}"
    living_room_se_ctr_blinds_tilt_position:
      friendly_name: "Living Room SE CTR Blinds Tilt Position"
      value_template: "{{ state_attr('cover.living_room_se_ctr_blinds', 'current_tilt_position') }}"
    living_room_ctr_blinds_tilt_position:
      friendly_name: "Living Room CTR Blinds Tilt Position"
      value_template: "{{ state_attr('cover.living_room_ctr_blinds', 'current_tilt_position') }}"
    living_room_nw_ctr_blinds_tilt_position:
      friendly_name: "Living Room NW CTR Blinds Tilt Position"
      value_template: "{{ state_attr('cover.living_room_nw_ctr_blinds', 'current_tilt_position') }}"
    living_room_nw_blinds_tilt_position:
      friendly_name: "Living Room NW Blinds Tilt Position"
      value_template: "{{ state_attr('cover.living_room_nw_blinds', 'current_tilt_position') }}"

