- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, make sure configuration file is encoded as UTF-8
  unit_of_measurement: "°F"
  value_template: '{{ ( value | multiply(0.0018) + 32 ) | round(1) }}'