- platform: mqtt
  name: "DTE Energy Bridge"
  state_topic: "event/metering/instantaneous_demand"
  unit_of_measurement: 'W'
  device_class: power
  state_class: measurement
  value_template: "{{ value_json.demand }}"
- platform: mqtt
  name: "DTE Energy Bridge Summary"
  state_topic: "event/metering/summation/minute"
  unit_of_measurement: 'W'
  device_class: power
  state_class: measurement
  value_template: "{{ value_json.value|round }}"
