- platform: template
  sensors:
    furnace_nw_zone_return_temperature_f:
      friendly_name: "Furnace NW Zone Return Temperature ºF"
      unit_of_measurement: 'ºF'
      value_template: "{{ (states('sensor.furnace_nw_zone_return_temperature') | float * 9.0/5.0+32.0) | round(1) }}"
      icon_template: "mdi:thermometer"
    furnace_se_zone_return_temperature_f:
      friendly_name: "Furnace SE Zone Return Temperature ºF"
      unit_of_measurement: 'ºF'
      value_template: "{{ (states('sensor.furnace_se_zone_return_temperature') | float * 9.0/5.0+32.0) | round(1) }}"
      icon_template: "mdi:thermometer"
    furnace_supply_temperature_f:
      friendly_name: "Furnace Supply Temperature ºF"
      unit_of_measurement: 'ºF'
      value_template: "{{ (states('sensor.furnace_supply_temperature') | float * 9.0/5.0+32.0) | round(1) }}"
      icon_template: "mdi:thermometer"
    furnace_flue_temperature_f:
      friendly_name: "Furnace Flue Temperature ºF"
      unit_of_measurement: 'ºF'
      value_template: "{{ (states('sensor.furnace_flue_temperature') | float * 9.0/5.0+32.0) | round(1) }}"
      icon_template: "mdi:thermometer"

